version: '3'

services:
  catdb:
    image: postgres:16
    environment:
      POSTGRES_DB: catdb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user 
      # PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"

