"""add cat and phrases tables

Revision ID: 52decefac641
Revises: 
Create Date: 2024-05-19 19:59:28.301683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52decefac641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('phrase',
    sa.Column('str_phrase', sa.String(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['cat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phrase')
    op.drop_table('cat')
    # ### end Alembic commands ###
